DEFAULT_HABITS = {
    'Vipassana': {'checked': 0, 'category': 'exercise'},
    'Python Hackerrank': {'checked': 0, 'category': 'computer'},
    'SQL Hackerrank': {'checked': 0, 'category': 'computer'},
    'SQL Vertabelo': {'checked': 0, 'category': 'computer'},
    'Linux': {'checked': 0, 'category': 'computer'},
    'Interview Question': {'checked': 0, 'category': 'general'},
    'Project': {'checked': 0, 'category': 'computer'},
    'CS Degree': {'checked': 0, 'category': 'computer'},
    '50 Pushups': {'checked': 0, 'category': 'exercise'},
    'OH Stretch': {'checked': 0, 'category': 'exercise'},
    '50 Situps': {'checked': 0, 'category': 'exercise'},
    '50 Squats': {'checked': 0, 'category': 'exercise'},
    'Philosophy': {'checked': 0, 'category': 'general'},
    'Exercise': {'checked': 0, 'category': 'exercise'},
    'Yoga': {'checked': 0, 'category': 'health'},
    'Protein Shake': {'checked': 0, 'category': 'health'},
    'Eat Healthy': {'checked': 0, 'category': 'health'},
    'Portion Control': {'checked': 0, 'category': 'health'},
}
