"""add scheduler_job_runs table

Revision ID: 08d5a3d4b957
Revises: d1e2f3a4b5c6
Create Date: 2026-03-15 18:31:38.848071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d5a3d4b957'
down_revision = 'd1e2f3a4b5c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduler_job_runs')),
    schema='admin'
    )
    op.create_index(op.f('ix_admin_scheduler_job_runs_job_id'), 'scheduler_job_runs', ['job_id'], unique=False, schema='admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_scheduler_job_runs_job_id'), table_name='scheduler_job_runs', schema='admin')
    op.drop_table('scheduler_job_runs', schema='admin')
    # ### end Alembic commands ###
