"""add personal_api_keys table

Revision ID: 6c8f9a0ef2cd
Revises: ebb7845c26d9
Create Date: 2026-03-04 13:20:01.262773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8f9a0ef2cd'
down_revision = 'ebb7845c26d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('hashed_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_personal_api_keys_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_api_keys')),
    sa.UniqueConstraint('hashed_key', name=op.f('uq_personal_api_keys_hashed_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_api_keys')
    # ### end Alembic commands ###
