"""Add a short display number to project_items

Project items and projects were the only resources keyed by UUID; tasks, books,
articles, events and countdowns all carry a short integer. The UUID is the right
primary key — items are created offline in todoui's SQLite and pushed, so the id
has to be collision-free without a round trip — but using that key as the human
handle put 36 characters of hex in every list row and every command a person or
an agent had to retype.

A key and a handle have different requirements: a key must be globally unique and
stable forever, a handle must be short enough to retype. This adds the handle and
leaves the key alone, which is what GitHub, Linear and Jira all do.

Backfilled in creation order so the oldest item is 1. The identity is BY DEFAULT
rather than ALWAYS so a restore can carry its own numbers; nothing in the write
path supplies one.

Revision ID: b8c9d0e1f2a3
Revises: a7b8c9d0e1f2
Create Date: 2026-08-07

"""

import sqlalchemy as sa
from alembic import op

revision: str = 'b8c9d0e1f2a3'
down_revision: str | None = 'a7b8c9d0e1f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('project_items', sa.Column('number', sa.BigInteger(), nullable=True))
    op.execute("""
        UPDATE project_items
        SET number = ordered.row_number
        FROM (
            SELECT id, row_number() OVER (ORDER BY created_at, id) AS row_number
            FROM project_items
        ) AS ordered
        WHERE project_items.id = ordered.id
    """)
    op.alter_column('project_items', 'number', nullable=False)
    # The identity has to be attached after the backfill: Postgres refuses to add
    # one to a nullable column, and adding it before would hand every existing row
    # a number from the sequence rather than its creation order.
    op.execute("""
        DO $$
        DECLARE
            next_number bigint;
        BEGIN
            SELECT COALESCE(MAX(number), 0) + 1 INTO next_number FROM project_items;
            EXECUTE format(
                'ALTER TABLE project_items ALTER COLUMN number ADD GENERATED BY DEFAULT AS IDENTITY (RESTART %s)',
                next_number
            );
        END $$;
    """)
    op.create_unique_constraint('uq_project_items_number', 'project_items', ['number'])


def downgrade() -> None:
    op.drop_constraint('uq_project_items_number', 'project_items', type_='unique')
    op.execute('ALTER TABLE project_items ALTER COLUMN number DROP IDENTITY IF EXISTS')
    op.drop_column('project_items', 'number')
