"""baseline schema

Revision ID: e010f859f025
Revises:
Create Date: 2026-03-14 00:18:59.900959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e010f859f025'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apartments')),
    schema='apartments'
    )
    op.create_index(op.f('ix_apartments_apartments_id'), 'apartments', ['id'], unique=False, schema='apartments')
    op.create_index(op.f('ix_apartments_apartments_name'), 'apartments', ['name'], unique=False, schema='apartments')
    op.create_table('article_failed_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_failed_imports'))
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('save_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_read_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('review_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('url', name=op.f('uq_articles_url'))
    )
    op.create_table('autotask_frequencies',
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_autotask_frequencies'))
    )
    op.execute(
        "INSERT INTO autotask_frequencies (name) VALUES "
        "('Biweekly'), ('Daily'), ('Monthly'), ('Quarterly'), "
        "('Semiannually'), ('Weekly'), ('Yearly')"
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('goodreads_url', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('sell_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('read_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_finish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('abandoned', sa.Boolean(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books')),
    sa.UniqueConstraint('goodreads_url', name=op.f('uq_books_goodreads_url'))
    )
    op.create_table('box_sizes',
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_box_sizes')),
    schema='box_packing'
    )
    op.execute(
        "INSERT INTO box_packing.box_sizes (name) VALUES "
        "('Bag'), ('Book'), ('Large'), ('Medium'), ('Misc'), "
        "('Monitor'), ('Sixteen'), ('Small'), ('UhaulSmall')"
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats')),
    sa.UniqueConstraint('name', name=op.f('uq_chats_name')),
    schema='chat'
    )
    op.create_table('countdowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countdowns'))
    )
    op.create_table('durations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_durations'))
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=256), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('attending', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    schema='habits'
    )
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('feeling', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal'))
    )
    op.create_table('jwt_refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('date_stored', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jwt_refresh_tokens'))
    )
    op.create_table('money_wasted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date_purchased', sa.Date(), nullable=True),
    sa.Column('date_wasted', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_money_wasted'))
    )
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio'))
    )
    op.create_table('task_categories',
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_task_categories'))
    )
    op.execute(
        "INSERT INTO task_categories (name) VALUES "
        "('Automotive'), ('Chore'), ('Computer'), ('Dingo'), ('Financial'), "
        "('Home'), ('Kitchen'), ('Learn'), ('Personal'), ('Purchase'), "
        "('Research'), ('Work')"
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alternative_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('alternative_id', name=op.f('uq_users_alternative_id')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('backup_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('backup_type', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('table_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('postgres_version', sa.Text(), nullable=True),
    sa.Column('database_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_backup_history_triggered_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_history')),
    sa.UniqueConstraint('filename', name=op.f('uq_backup_history_filename')),
    schema='admin'
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apt_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_str', sa.String(), nullable=True),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('value_float', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['apt_id'], ['apartments.apartments.id'], name=op.f('fk_features_apt_id_apartments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_features')),
    schema='apartments'
    )
    op.create_index(op.f('ix_apartments_features_id'), 'features', ['id'], unique=False, schema='apartments')
    op.create_table('autotasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=False),
    sa.Column('first_run_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_run_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['task_categories.name'], name=op.f('fk_autotasks_category_task_categories')),
    sa.ForeignKeyConstraint(['frequency'], ['autotask_frequencies.name'], name=op.f('fk_autotasks_frequency_autotask_frequencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_autotasks'))
    )
    op.create_table('boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.Text(), nullable=False),
    sa.Column('essential', sa.Boolean(), nullable=False),
    sa.Column('warm', sa.Boolean(), nullable=False),
    sa.Column('liquid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['size'], ['box_packing.box_sizes.name'], name=op.f('fk_boxes_size_box_sizes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boxes')),
    sa.UniqueConstraint('number', name=op.f('uq_boxes_number')),
    schema='box_packing'
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chats.id'], name=op.f('fk_messages_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    schema='chat'
    )
    op.create_table('duration_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['duration_id'], ['durations.id'], name=op.f('fk_duration_notes_duration_id_durations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duration_notes'))
    )
    op.create_table('completed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('complete_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['habits.categories.id'], name=op.f('fk_completed_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_completed')),
    schema='habits'
    )
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['habits.categories.id'], name=op.f('fk_habits_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habits')),
    schema='habits'
    )
    op.create_table('personal_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('hashed_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_personal_api_keys_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_api_keys')),
    sa.UniqueConstraint('hashed_key', name=op.f('uq_personal_api_keys_hashed_key'))
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('add_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('complete_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['task_categories.name'], name=op.f('fk_tasks_category_task_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_table('backup_restores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backup_id', sa.Integer(), nullable=False),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restored_to_environment', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('restored_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['backup_id'], ['admin.backup_history.id'], name=op.f('fk_backup_restores_backup_id_backup_history')),
    sa.ForeignKeyConstraint(['restored_by_user_id'], ['users.id'], name=op.f('fk_backup_restores_restored_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_restores')),
    schema='admin'
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('essential', sa.Boolean(), nullable=False),
    sa.Column('warm', sa.Boolean(), nullable=False),
    sa.Column('liquid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['box_packing.boxes.id'], name=op.f('fk_items_box_id_boxes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    schema='box_packing'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items', schema='box_packing')
    op.drop_table('backup_restores', schema='admin')
    op.drop_table('tasks')
    op.drop_table('personal_api_keys')
    op.drop_table('habits', schema='habits')
    op.drop_table('completed', schema='habits')
    op.drop_table('duration_notes')
    op.drop_table('messages', schema='chat')
    op.drop_table('boxes', schema='box_packing')
    op.drop_table('autotasks')
    op.drop_index(op.f('ix_apartments_features_id'), table_name='features', schema='apartments')
    op.drop_table('features', schema='apartments')
    op.drop_table('backup_history', schema='admin')
    op.drop_table('users')
    op.drop_table('task_categories')
    op.drop_table('portfolio')
    op.drop_table('money_wasted')
    op.drop_table('jwt_refresh_tokens')
    op.drop_table('journal')
    op.drop_table('categories', schema='habits')
    op.drop_table('events')
    op.drop_table('durations')
    op.drop_table('countdowns')
    op.drop_table('chats', schema='chat')
    op.drop_table('box_sizes', schema='box_packing')
    op.drop_table('books')
    op.drop_table('autotask_frequencies')
    op.drop_table('articles')
    op.drop_table('article_failed_imports')
    op.drop_index(op.f('ix_apartments_apartments_name'), table_name='apartments', schema='apartments')
    op.drop_index(op.f('ix_apartments_apartments_id'), table_name='apartments', schema='apartments')
    op.drop_table('apartments', schema='apartments')
    # ### end Alembic commands ###
