name: Sync Documentation Code

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.go'
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
  workflow_dispatch:

jobs:
  sync-docs:
    name: Sync Code Snippets in Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tree-sitter  # Optional, for better language support

      - name: Run AST Code Sync
        run: |
          python -m tools.ast-code-sync.code_sync docs --base-path .

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: Update code snippets in documentation"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
