"""The schema the migrations build is the schema the models declare.

This runs `alembic check` through `env.py` against the session's database,
which pytest has migrated to head.

`LEGACY_TABLES` are still created by the migrations and mapped by no model.
Each holds production rows, so they leave the schema through their own
release. The test fails once one is gone and still listed here.
"""

from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected

from ichrisbirch.database.initialization import alembic_config
from tests.utils.database import test_settings

LEGACY_TABLES = {
    ('apartments', 'apartments'),
    ('apartments', 'features'),
    (None, 'journal'),
    (None, 'portfolio'),
}


def legacy_table_dropped_by(diff) -> tuple[str | None, str] | None:
    if not isinstance(diff, tuple):
        return None
    if diff[0] == 'remove_table':
        table = diff[1]
    elif diff[0] == 'remove_index':
        table = diff[1].table
    else:
        return None
    name = (table.schema, table.name)
    return name if name in LEGACY_TABLES else None


def test_alembic_check_proposes_nothing_but_dropping_the_legacy_tables():
    try:
        command.check(alembic_config(test_settings))
        diffs = []
    except AutogenerateDiffsDetected as detected:
        diffs = detected.diffs

    drift = [diff for diff in diffs if legacy_table_dropped_by(diff) is None]
    assert not drift, f'the models and the migrated schema differ: {drift}'

    still_present = {legacy_table_dropped_by(diff) for diff in diffs}
    assert still_present == LEGACY_TABLES, f'gone from the schema, so remove from LEGACY_TABLES: {LEGACY_TABLES - still_present}'
