"""The identity → shared sequence switch on `project_items.number`, run against rows.

Every other check runs `upgrade()` on an empty `project_items`, where the
sequence starts at 1 whatever the `setval` says. Production holds items, and a
sequence starting below the highest number would hand a new issue a number an
item already has.

These build the pre-migration shape in a temporary table, run the statements the
migration runs, and insert the way the release still serving during a deploy
does: without a number.
"""

import pytest
import sqlalchemy as sa

UPGRADE = [
    'CREATE TEMP SEQUENCE probe_numbers AS bigint',
    "SELECT setval('probe_numbers', COALESCE((SELECT MAX(number) FROM probe), 0) + 1, false)",
    'ALTER TABLE probe ALTER COLUMN number DROP IDENTITY IF EXISTS',
    "ALTER TABLE probe ALTER COLUMN number SET DEFAULT nextval('probe_numbers')",
]

DOWNGRADE = [
    'ALTER TABLE probe ALTER COLUMN number DROP DEFAULT',
    """
    DO $$
    DECLARE
        next_number bigint;
    BEGIN
        SELECT COALESCE(MAX(number), 0) + 1 INTO next_number FROM probe;
        EXECUTE format(
            'ALTER TABLE probe ALTER COLUMN number ADD GENERATED BY DEFAULT AS IDENTITY (RESTART %s)',
            next_number
        );
    END $$;
    """,
]


@pytest.fixture
def conn(factory_session):
    conn = factory_session.connection()
    conn.execute(sa.text('CREATE TEMP TABLE probe (number bigint GENERATED BY DEFAULT AS IDENTITY, title text) ON COMMIT DROP'))
    conn.execute(sa.text("INSERT INTO probe (title) VALUES ('one'), ('two'), ('three')"))
    # A number set by hand, above what the identity has issued, as an imported row would be.
    conn.execute(sa.text("INSERT INTO probe (number, title) VALUES (40, 'imported')"))
    return conn


def run(conn, statements: list[str]) -> None:
    for statement in statements:
        conn.execute(sa.text(statement))


def insert_without_number(conn, title: str) -> int:
    return conn.execute(sa.text('INSERT INTO probe (title) VALUES (:title) RETURNING number'), {'title': title}).scalar_one()


def test_the_sequence_starts_above_the_highest_number(conn):
    run(conn, UPGRADE)
    assert insert_without_number(conn, 'after the switch') == 41


def test_a_second_table_drawing_from_the_sequence_never_repeats_a_number(conn):
    run(conn, UPGRADE)
    issue_number = conn.execute(sa.text("SELECT nextval('probe_numbers')")).scalar_one()
    assert (issue_number, insert_without_number(conn, 'item')) == (41, 42)


def test_the_downgrade_restores_an_identity_above_every_number(conn):
    run(conn, UPGRADE)
    insert_without_number(conn, 'issued by the sequence')
    run(conn, DOWNGRADE)
    assert insert_without_number(conn, 'issued by the identity') == 42
