box_list = [
    {
        "name": "Computers",
        "size": "medium",
        "liquid": False,
        "warm": True,
        "essential": False,
    },
    {
        "name": "Monitors and Clock",
        "size": "xlarge",
        "liquid": False,
        "warm": True,
        "essential": False,
    },
    {
        "name": "Food Staples",
        "size": "medium",
        "liquid": True,
        "warm": True,
        "essential": True,
    },
    {
        "name": "The Box with the Longest Name Ever in the World",
        "size": "medium",
        "liquid": False,
        "warm": False,
        "essential": False,
    },
    {
        "name": "D",
        "size": "medium",
        "liquid": True,
        "warm": False,
        "essential": True,
    },
    {
        "name": "K Cups",
        "size": "medium",
        "liquid": False,
        "warm": True,
        "essential": False,
    },
    {
        "name": "TV",
        "size": "xlarge",
        "liquid": False,
        "warm": True,
        "essential": False,
    },
    {
        "name": "Widescreen",
        "size": "medium",
        "liquid": False,
        "warm": False,
        "essential": False,
    },
    {
        "name": "The Box with the Longest Name Ever in the World",
        "size": "medium",
        "liquid": False,
        "warm": False,
        "essential": False,
    },
    {
        "name": "Pills",
        "size": "medium",
        "liquid": True,
        "warm": False,
        "essential": True,
    },
    {
        "name": "Random",
        "size": "medium",
        "liquid": False,
        "warm": True,
        "essential": False,
    },
    {
        "name": "Kitchen 1",
        "size": "xlarge",
        "liquid": False,
        "warm": True,
        "essential": False,
    },
    {
        "name": "Pans",
        "size": "medium",
        "liquid": False,
        "warm": False,
        "essential": False,
    },
    {
        "name": "Pots",
        "size": "medium",
        "liquid": False,
        "warm": False,
        "essential": False,
    },
    {
        "name": "Liquids",
        "size": "medium",
        "liquid": True,
        "warm": False,
        "essential": True,
    },
]
item_list = [
    {
        'box_id': 1,
        'name': 'Battery Backup',
        "liquid": True,
        "warm": False,
        "essential": True,
    },
    {
        'box_id': 1,
        'name': 'Battery Backup1',
        "liquid": True,
        "warm": False,
        "essential": True,
    },
    {
        'box_id': 1,
        'name': 'Some cords that have a long name that messes it up',
        "liquid": True,
        "warm": False,
        "essential": False,
    },
    {
        'box_id': 5,
        'name': 'S',
        "liquid": True,
        "warm": True,
        "essential": True,
    },
    {
        'box_id': 5,
        'name': 'cords',
        "liquid": False,
        "warm": False,
        "essential": True,
    },
    {
        'box_id': 4,
        'name': 'Shite',
        "liquid": False,
        "warm": False,
        "essential": False,
    },
    {
        'box_id': 2,
        'name': 'Some cords that have a long name that messes it up',
        "liquid": True,
        "warm": False,
        "essential": False,
    },
    {
        'box_id': 2,
        'name': 'S',
        "liquid": True,
        "warm": True,
        "essential": True,
    },
    {
        'box_id': 5,
        'name': 'lamp',
        "liquid": False,
        "warm": False,
        "essential": True,
    },
    {
        'box_id': 3,
        'name': 'Shite',
        "liquid": False,
        "warm": False,
        "essential": False,
    },
    {
        'box_id': 2,
        'name': 'pills',
        "liquid": True,
        "warm": False,
        "essential": True,
    },
    {
        'box_id': 2,
        'name': 'Battery Backup1',
        "liquid": True,
        "warm": False,
        "essential": True,
    },
    {
        'box_id': 3,
        'name': 'Some cords that have a long name that messes it up',
        "liquid": True,
        "warm": False,
        "essential": False,
    },
    {
        'box_id': 1,
        'name': 'S',
        "liquid": True,
        "warm": True,
        "essential": True,
    },
    {
        'box_id': 2,
        'name': 'spoon',
        "liquid": False,
        "warm": False,
        "essential": True,
    },
    {
        'box_id': 3,
        'name': 'Shite',
        "liquid": False,
        "warm": False,
        "essential": False,
    },
    {
        'box_id': 4,
        'name': 'Some cords that have a long name that messes it up',
        "liquid": True,
        "warm": False,
        "essential": False,
    },
    {
        'box_id': 5,
        'name': 'S',
        "liquid": True,
        "warm": True,
        "essential": True,
    },
    {
        'box_id': 1,
        'name': 'Do you want some more?',
        "liquid": False,
        "warm": False,
        "essential": True,
    },
    {
        'box_id': 2,
        'name': 'Shite',
        "liquid": False,
        "warm": False,
        "essential": False,
    },
    {
        'box_id': 2,
        'name': 'Battery Backup',
        "liquid": True,
        "warm": True,
        "essential": True,
    },
    {
        'box_id': 3,
        'name': 'Battery Backup1',
        "liquid": True,
        "warm": False,
        "essential": True,
    },
    {
        'box_id': 4,
        'name': 'Some cords that have a long name that messes it up',
        "liquid": True,
        "warm": True,
        "essential": False,
    },
    {
        'box_id': 1,
        'name': 'S',
        "liquid": True,
        "warm": True,
        "essential": True,
    },
    {
        'box_id': 1,
        'name': 'Do you want some more?',
        "liquid": False,
        "warm": True,
        "essential": True,
    },
    {
        'box_id': 2,
        'name': 'Shite',
        "liquid": False,
        "warm": False,
        "essential": False,
    },
    {
        'box_id': 3,
        'name': 'Some cords that have a long name that messes it up',
        "liquid": True,
        "warm": False,
        "essential": False,
    },
    {
        'box_id': 4,
        'name': 'S',
        "liquid": True,
        "warm": True,
        "essential": True,
    },
    {
        'box_id': 5,
        'name': 'Do you want some more?',
        "liquid": False,
        "warm": False,
        "essential": True,
    },
    {
        'box_id': 1,
        'name': 'Shite',
        "liquid": False,
        "warm": False,
        "essential": False,
    },
    {
        'box_id': 3,
        'name': 'Battery Backup',
        "liquid": True,
        "warm": False,
        "essential": True,
    },
    {
        'box_id': 3,
        'name': 'Battery Backup1',
        "liquid": True,
        "warm": False,
        "essential": True,
    },
    {
        'box_id': 2,
        'name': 'Some cords that have a long name that messes it up',
        "liquid": True,
        "warm": False,
        "essential": False,
    },
    {
        'box_id': 2,
        'name': 'S',
        "liquid": True,
        "warm": True,
        "essential": True,
    },
    {
        'box_id': 1,
        'name': 'Do you want some more?',
        "liquid": False,
        "warm": False,
        "essential": True,
    },
    {
        'box_id': 4,
        'name': 'Shite',
        "liquid": False,
        "warm": False,
        "essential": False,
    },
    {
        'box_id': 5,
        'name': 'Some cords that have a long name that messes it up',
        "liquid": True,
        "warm": False,
        "essential": False,
    },
    {
        'box_id': 1,
        'name': 'S',
        "liquid": True,
        "warm": True,
        "essential": True,
    },
    {
        'box_id': 2,
        'name': 'Do you want some more?',
        "liquid": False,
        "warm": False,
        "essential": True,
    },
    {
        'box_id': 3,
        'name': 'Shite',
        "liquid": False,
        "warm": False,
        "essential": False,
    },
]
