"""v0.4.1

Revision ID: ef32323adb95
Revises: 773b6a901410
Create Date: 2022-08-30 19:44:05.469746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef32323adb95'
down_revision = '773b6a901410'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='apartments'
    )
    op.create_index(op.f('ix_apartments_apartments_id'), 'apartments', ['id'], unique=False, schema='apartments')
    op.create_index(op.f('ix_apartments_apartments_name'), 'apartments', ['name'], unique=False, schema='apartments')
    op.create_table('boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('essential', sa.Boolean(), nullable=True),
    sa.Column('warm', sa.Boolean(), nullable=True),
    sa.Column('liquid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='box_packing'
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='habits'
    )
    op.create_table('completed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='habits'
    )
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='habits'
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apt_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_str', sa.String(), nullable=True),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('value_float', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['apt_id'], ['apartments.apartments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='apartments'
    )
    op.create_index(op.f('ix_apartments_features_id'), 'features', ['id'], unique=False, schema='apartments')
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('essential', sa.Boolean(), nullable=False),
    sa.Column('warm', sa.Boolean(), nullable=False),
    sa.Column('liquid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['box_packing.boxes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='box_packing'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items', schema='box_packing')
    op.drop_index(op.f('ix_apartments_features_id'), table_name='features', schema='apartments')
    op.drop_table('features', schema='apartments')
    op.drop_table('habits', schema='habits')
    op.drop_table('completed', schema='habits')
    op.drop_table('categories', schema='habits')
    op.drop_table('boxes', schema='box_packing')
    op.drop_index(op.f('ix_apartments_apartments_name'), table_name='apartments', schema='apartments')
    op.drop_index(op.f('ix_apartments_apartments_id'), table_name='apartments', schema='apartments')
    op.drop_table('apartments', schema='apartments')
    # ### end Alembic commands ###
