import re

import httpx
import pendulum
import structlog
from fastapi import APIRouter
from fastapi import Depends
from fastapi import HTTPException
from fastapi import Request
from fastapi import status

from ichrisbirch.config import Settings
from ichrisbirch.config import get_settings
from ichrisbirch.schemas.github_issue import GithubIssueCreate
from ichrisbirch.schemas.github_issue import GithubIssueResponse

logger = structlog.get_logger()

router = APIRouter()


def _format_issue_body(issue: GithubIssueCreate, request: Request) -> str:
    user_agent = request.headers.get('User-Agent', '')
    ua_parts = [f'\t - {part.strip()})' for part in re.split(r'\)', user_agent) if part.strip()]

    body = f"""{issue.description}


---
### Autogenerated Details

**Date:** {pendulum.now().isoformat()}

**Page:** {request.headers.get('Referer', 'unknown')}

**IP Address:** {request.headers.get('X-Forwarded-For', request.client.host if request.client else 'unknown')}

**User-Agent:**
{chr(10).join(ua_parts)}"""
    return body


@router.post('/', response_model=GithubIssueResponse, status_code=status.HTTP_201_CREATED)
async def create_github_issue(
    issue: GithubIssueCreate,
    request: Request,
    settings: Settings = Depends(get_settings),
):
    body = _format_issue_body(issue, request)
    data = {'title': issue.title, 'body': body, 'labels': issue.labels}
    logger.info('github_issue_creating', title=issue.title, labels=issue.labels)

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                settings.github.api_url_issues,
                json=data,
                headers=settings.github.api_headers,
            )
            response.raise_for_status()
    except httpx.HTTPStatusError as e:
        logger.error('github_issue_api_error', status=e.response.status_code, body=e.response.text)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f'GitHub API error: {e.response.status_code}',
        ) from e
    except httpx.HTTPError as e:
        logger.error('github_issue_request_error', error=str(e))
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f'Failed to reach GitHub API: {e}',
        ) from e

    result = response.json()
    logger.info('github_issue_created', number=result['number'], url=result['html_url'])
    return GithubIssueResponse(
        html_url=result['html_url'],
        number=result['number'],
        title=result['title'],
    )
