#!/usr/bin/env bash
# Write the Traefik services file that points every app service at one
# blue/green color.
#
# Routers live in routing.yml and are git-tracked. Services are deploy-time
# state and live in the file this writes; Traefik merges both from the
# directory provider.
#
# Both the deploy and the rollback path need this file and each used to carry
# its own copy of the YAML. A service added to one and missed in the other
# routes production traffic at a container that is not there.
#
# The output path is an argument because the two callers resolve the install
# directory differently — the deploy script hardcodes it, the CLI derives it
# from its own location — and those agree only on the production host.

set -euo pipefail

if [[ $# -ne 3 ]]; then
  echo "usage: $(basename "$0") <color> <output-file> <generated-by>" >&2
  exit 1
fi

color="$1"
output_file="$2"
generated_by="$3"
tmp_file="${output_file}.tmp"

cat >"$tmp_file" <<EOF
# Generated by ${generated_by} — DO NOT EDIT
# Active color: ${color}

http:
  services:
    api:
      loadBalancer:
        servers:
          - url: "http://icb-${color}-api:8000"
    vue:
      loadBalancer:
        servers:
          - url: "http://icb-${color}-vue:80"
EOF

# Atomic swap — Traefik watches the directory and reloads within 1-2 seconds
mv "$tmp_file" "$output_file"
