name: Retrieve Webserver Key and IP
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      webserver_ip:
        value: ${{ jobs.retrieve-webserver-key-and-ip.outputs.webserver_ip }}


jobs:
  retrieve-webserver-key-and-ip:
    name: Retrieve Webserver Key and IP
    runs-on: ubuntu-latest
    outputs:
      webserver_ip: ${{ steps.terraform_output.outputs.ELASTIC_IP }}

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-${{ github.event.repository.name }}-role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Retrieve SSH Key from S3 Bucket
        id: get_ssh_key
        run: |
          aws s3 cp s3://ichrisbirch-webserver-keys/${{ vars.SSH_KEY_FILENAME }} ${{ vars.SSH_KEY_FILENAME }}
          chmod 600 ${{ vars.SSH_KEY_FILENAME }}
        shell: bash

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ github.workspace }}/terraform

      - name: Get Elastic IP from Terraform Output
        id: terraform_output
        run: echo "ELASTIC_IP=$(terraform output -raw webserver_elastic_ip)" >> "$GITHUB_OUTPUT"
        working-directory: ${{ github.workspace }}/terraform
